[versions]
junit4 = "4.13.2"
allure = "2.30.0"
assertj = "3.27.6"
testcontainers = "1.21.3"
aspectj = "1.9.24"

[libraries]
junit4 = {module = "junit:junit", version.ref = "junit4"}

allure-junit4-adapter = {module = "io.qameta.allure:allure-junit4", version.ref = "allure"}
allure-junit4-aspect = {module = "io.qameta.allure:allure-junit4-aspect", version.ref = "allure"}
allure-assertj = {module = "io.qameta.allure:allure-assertj", version.ref = "allure"}

assertj = {module = "org.assertj:assertj-core", version.ref = "assertj"}

testcontainers-core = {module = "org.testcontainers:testcontainers", version.ref = "testcontainers"}

testcontainernginx = {module = "org.testcontainers:nginx", version.ref = 'testcontainers'}

junit-system-rules = {module = "com.github.stefanbirkner:system-rules", version = "1.19.0"}

aspectj-weaver = {module = "org.aspectj:aspectjweaver", version.ref = "aspectj"}

